<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>108629f2-ca1f-4180-86c8-f1ea506288e9</UserSecretsId>
		<AssemblyName>EduAdvisor.API</AssemblyName>
		<RootNamespace>EduAdvisor.API</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="9.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Logs\" />
		<Folder Include="wwwroot\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EduAdvisor.Application\EduAdvisor.Application.csproj" />
		<ProjectReference Include="..\EduAdvisor.Infrastructure\EduAdvisor.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="EmailTemplates\EmailConfirmation.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="EmailTemplates\ForgetPassword.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>